# Generated by Django 4.0.1 on 2022-01-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_data',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='email')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('photo', models.ImageField(upload_to='', verbose_name='photo')),
                ('full_name', models.CharField(max_length=99, verbose_name='full_name')),
                ('address', models.CharField(max_length=99, verbose_name='address')),
                ('cellphone', models.CharField(max_length=11, verbose_name='cellphone')),
                ('birthday', models.DateField(verbose_name='birthday')),
                ('bplace', models.CharField(max_length=99, verbose_name='bplace')),
                ('civilstatus', models.CharField(max_length=99, verbose_name='civilstatus')),
                ('citizenship', models.CharField(max_length=99, verbose_name='citizenship')),
                ('religion', models.CharField(max_length=99, verbose_name='religion')),
                ('e_contact', models.CharField(max_length=99, verbose_name='e_contact')),
                ('e_no', models.CharField(max_length=11, verbose_name='e_no')),
                ('elementary', models.CharField(max_length=99, verbose_name='elementary')),
                ('elementary_grad', models.CharField(max_length=99, verbose_name='elementary_grad')),
                ('highschool', models.CharField(max_length=99, verbose_name='highschool')),
                ('highschool_grad', models.CharField(max_length=99, verbose_name='highschool_grad')),
                ('college', models.CharField(max_length=99, verbose_name='college')),
                ('college_grad', models.CharField(max_length=99, verbose_name='college_grad')),
                ('company1', models.CharField(max_length=99, verbose_name='company1')),
                ('position1', models.CharField(max_length=99, verbose_name='position1')),
                ('from1', models.DateField(verbose_name='from1')),
                ('to1', models.DateField(verbose_name='to1')),
                ('company2', models.CharField(max_length=99, verbose_name='company2')),
                ('position2', models.CharField(max_length=99, verbose_name='position2')),
                ('from2', models.DateField(verbose_name='from2')),
                ('to2', models.DateField(verbose_name='to2')),
                ('philhealth', models.CharField(max_length=12, verbose_name='philhealth')),
                ('pagibig', models.CharField(max_length=12, verbose_name='pagibig')),
                ('TIN', models.CharField(max_length=9, verbose_name='TIN')),
                ('NBI', models.CharField(max_length=6, verbose_name='NBI')),
                ('SSS', models.CharField(max_length=10, verbose_name='SSS')),
                ('med_record', models.CharField(max_length=6, verbose_name='med_record')),
                ('applyingfor', models.CharField(max_length=99, verbose_name='applyingfor')),
                ('job', models.CharField(max_length=99, verbose_name='job')),
                ('account_type', models.CharField(max_length=99, verbose_name='account_type')),
            ],
        ),
    ]
