# Generated by Django 4.0.1 on 2022-05-18 04:59

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_registration',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.EmailField(default='', max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='username')),
                ('password', models.CharField(default='', max_length=20, verbose_name='password')),
                ('password1', models.CharField(default='', max_length=20, verbose_name='password1')),
                ('photo', models.ImageField(null=True, upload_to='images/', verbose_name='photo')),
                ('first_name', models.CharField(default='', max_length=99, verbose_name='first_name')),
                ('middle_name', models.CharField(default='', max_length=99, verbose_name='middle_name')),
                ('last_name', models.CharField(default='', max_length=99, verbose_name='last_name')),
                ('address', models.CharField(max_length=99, verbose_name='address')),
                ('cellphone', models.CharField(max_length=11, verbose_name='cellphone')),
                ('birthday', models.DateField(verbose_name='birthday')),
                ('applyingfor', models.CharField(choices=[('Choice1', 'Website Developersss')], default='', max_length=99, verbose_name='applyingfor')),
                ('job', models.CharField(default='Applicant', max_length=99, verbose_name='job')),
                ('employment_status', models.CharField(default='Not yet Employed', max_length=99, verbose_name='job')),
                ('account_type', models.CharField(max_length=99, verbose_name='account_type')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='job_listing',
            fields=[
                ('jtitle', models.CharField(max_length=99, primary_key=True, serialize=False, verbose_name='jtitle')),
                ('jdesc', models.TextField(max_length=300, verbose_name='jdesc')),
                ('jobreq1', models.CharField(default='No Diploma Needed', max_length=99, verbose_name='jobreq1')),
                ('jobreq2', models.CharField(default='No Reference Needed', max_length=99, verbose_name='jobreq2')),
                ('salary', models.PositiveIntegerField(verbose_name='salary')),
            ],
        ),
        migrations.CreateModel(
            name='other_info',
            fields=[
                ('email', models.ForeignKey(default='user@email.com', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bplace', models.CharField(max_length=99, null=True, verbose_name='bplace')),
                ('civilstatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed')], max_length=99, null=True, verbose_name='civilstatus')),
                ('citizenship', models.CharField(max_length=99, null=True, verbose_name='citizenship')),
                ('religion', models.CharField(max_length=99, null=True, verbose_name='religion')),
                ('e_contact', models.CharField(max_length=99, null=True, verbose_name='e_contact')),
                ('e_no', models.CharField(max_length=99, null=True, verbose_name='e_no')),
                ('elementary', models.CharField(max_length=99, null=True, verbose_name='elementary')),
                ('elementary_grad', models.CharField(max_length=99, null=True, verbose_name='elementary_grad')),
                ('highschool', models.CharField(max_length=99, null=True, verbose_name='highschool')),
                ('highschool_grad', models.CharField(max_length=99, null=True, verbose_name='highschool_grad')),
                ('college', models.CharField(max_length=99, null=True, verbose_name='college')),
                ('college_grad', models.CharField(max_length=99, null=True, verbose_name='college_grad')),
                ('company1', models.CharField(max_length=99, null=True, verbose_name='company1')),
                ('position1', models.CharField(max_length=99, null=True, verbose_name='position1')),
                ('from1', models.CharField(max_length=99, null=True, verbose_name='from_1')),
                ('to1', models.CharField(default='', max_length=99, null=True, verbose_name='to_1')),
                ('company2', models.CharField(default='', max_length=99, null=True, verbose_name='company2')),
                ('position2', models.CharField(default='', max_length=99, verbose_name='position2')),
                ('from2', models.CharField(default='', max_length=99, null=True, verbose_name='from_2')),
                ('to2', models.CharField(default='', max_length=99, null=True, verbose_name='to_2')),
                ('ref1', models.CharField(default='', max_length=99, null=True, verbose_name='ref1')),
                ('refcon1', models.CharField(default='', max_length=99, null=True, verbose_name='refcon1')),
                ('refpos1', models.CharField(default='', max_length=99, null=True, verbose_name='refpos1')),
                ('refcom1', models.CharField(default='', max_length=99, null=True, verbose_name='refcom1')),
                ('ref2', models.CharField(default='', max_length=99, null=True, verbose_name='ref2')),
                ('refcon2', models.CharField(default='', max_length=99, null=True, verbose_name='refcon2')),
                ('refpos2', models.CharField(default='', max_length=99, null=True, verbose_name='refpos2')),
                ('refcom2', models.CharField(default='', max_length=99, null=True, verbose_name='refcom2')),
                ('philhealth', models.CharField(max_length=99, null=True, verbose_name='philhealth')),
                ('pagibig', models.CharField(max_length=99, null=True, verbose_name='pagibig')),
                ('TIN', models.CharField(max_length=99, null=True, verbose_name='TIN')),
                ('NBI', models.CharField(max_length=99, null=True, verbose_name='NBI')),
                ('SSS', models.CharField(max_length=99, null=True, verbose_name='SSS')),
                ('med_record', models.CharField(max_length=6, null=True, verbose_name='med_record')),
                ('signature', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='signature')),
            ],
        ),
        migrations.CreateModel(
            name='interview',
            fields=[
                ('email', models.ForeignKey(default='user@email.com', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(default='', max_length=99, null=True, verbose_name='first_name')),
                ('middle_name', models.CharField(default='', max_length=99, null=True, verbose_name='middle_name')),
                ('last_name', models.CharField(default='', max_length=99, null=True, verbose_name='last_name')),
                ('date_time', models.DateTimeField(null=True, verbose_name='date_time')),
                ('jitle', models.ForeignKey(default='job title', max_length=99, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobweb.job_listing', verbose_name='jtitle')),
            ],
        ),
    ]
