# Generated by Django 4.0.1 on 2022-04-14 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_registration',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='email')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('photo', models.ImageField(upload_to='', verbose_name='photo')),
                ('first_name', models.CharField(default='', max_length=99, verbose_name='first_name')),
                ('middle_name', models.CharField(default='', max_length=99, verbose_name='middle_name')),
                ('last_name', models.CharField(default='', max_length=99, verbose_name='last_name')),
                ('address', models.CharField(max_length=99, verbose_name='address')),
                ('cellphone', models.CharField(max_length=11, verbose_name='cellphone')),
                ('birthday', models.DateField(verbose_name='birthday')),
            ],
        ),
        migrations.CreateModel(
            name='job_listing',
            fields=[
                ('jtitle', models.CharField(max_length=99, primary_key=True, serialize=False, verbose_name='jtitle')),
                ('jdesc', models.TextField(max_length=300, verbose_name='jdesc')),
                ('jobreq1', models.CharField(default='No Diploma Needed', max_length=99, verbose_name='jobreq1')),
                ('jobreq2', models.CharField(default='No Reference Needed', max_length=99, verbose_name='jobreq2')),
                ('salary', models.PositiveIntegerField(verbose_name='salary')),
            ],
        ),
        migrations.CreateModel(
            name='interview',
            fields=[
                ('email', models.ForeignKey(default='user@email.com', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jobweb.account_registration')),
                ('name', models.CharField(max_length=99, verbose_name='name')),
                ('date_time', models.DateField(verbose_name='date_time')),
                ('jitle', models.ForeignKey(default='job title', max_length=99, on_delete=django.db.models.deletion.CASCADE, to='jobweb.job_listing', verbose_name='jtitle')),
            ],
        ),
        migrations.CreateModel(
            name='other_info',
            fields=[
                ('email', models.ForeignKey(default='user@email.com', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jobweb.account_registration')),
                ('bplace', models.CharField(max_length=99, verbose_name='bplace')),
                ('civilstatus', models.CharField(max_length=99, verbose_name='civilstatus')),
                ('citizenship', models.CharField(max_length=99, verbose_name='citizenship')),
                ('religion', models.CharField(max_length=99, verbose_name='religion')),
                ('e_contact', models.CharField(max_length=99, verbose_name='e_contact')),
                ('e_no', models.CharField(max_length=11, verbose_name='e_no')),
                ('elementary', models.CharField(max_length=99, verbose_name='elementary')),
                ('elementary_grad', models.CharField(max_length=99, verbose_name='elementary_grad')),
                ('highschool', models.CharField(max_length=99, verbose_name='highschool')),
                ('highschool_grad', models.CharField(max_length=99, verbose_name='highschool_grad')),
                ('college', models.CharField(max_length=99, verbose_name='college')),
                ('college_grad', models.CharField(max_length=99, verbose_name='college_grad')),
                ('company1', models.CharField(max_length=99, verbose_name='company1')),
                ('position1', models.CharField(max_length=99, verbose_name='position1')),
                ('from1', models.CharField(max_length=99, verbose_name='from_1')),
                ('to1', models.CharField(default='', max_length=99, verbose_name='to_1')),
                ('company2', models.CharField(default='', max_length=99, verbose_name='company2')),
                ('position2', models.CharField(max_length=99, verbose_name='position2')),
                ('from2', models.CharField(default='', max_length=99, verbose_name='from_2')),
                ('to2', models.CharField(default='', max_length=99, verbose_name='to_2')),
                ('ref1', models.CharField(default='', max_length=99, verbose_name='ref1')),
                ('refcon1', models.CharField(default='', max_length=11, verbose_name='refcon1')),
                ('refpos1', models.CharField(default='', max_length=99, verbose_name='refpos1')),
                ('refcom1', models.CharField(default='', max_length=99, verbose_name='refcom1')),
                ('ref2', models.CharField(default='', max_length=99, verbose_name='ref2')),
                ('refcon2', models.CharField(default='', max_length=11, verbose_name='refcon2')),
                ('refpos2', models.CharField(default='', max_length=99, verbose_name='refpos2')),
                ('refcom2', models.CharField(default='', max_length=99, verbose_name='refcom2')),
                ('philhealth', models.CharField(max_length=12, verbose_name='philhealth')),
                ('pagibig', models.CharField(max_length=12, verbose_name='pagibig')),
                ('TIN', models.CharField(max_length=9, verbose_name='TIN')),
                ('NBI', models.CharField(max_length=6, verbose_name='NBI')),
                ('SSS', models.CharField(max_length=10, verbose_name='SSS')),
                ('med_record', models.CharField(max_length=6, verbose_name='med_record')),
                ('signature', models.ImageField(default='', upload_to='', verbose_name='signature')),
            ],
        ),
        migrations.DeleteModel(
            name='user_register',
        ),
    ]
