# Generated by Django 4.0.1 on 2022-04-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0002_account_registration_job_listing_interview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_registration',
            name='password',
        ),
        migrations.AddField(
            model_name='account_registration',
            name='account_type',
            field=models.CharField(default='Applicant', max_length=99, verbose_name='account_type'),
        ),
        migrations.AddField(
            model_name='account_registration',
            name='applyingfor',
            field=models.CharField(default='', max_length=99, verbose_name='applyingfor'),
        ),
        migrations.AddField(
            model_name='account_registration',
            name='job',
            field=models.CharField(default='Applicant', max_length=99, verbose_name='job'),
        ),
        migrations.AddField(
            model_name='account_registration',
            name='password1',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='password1'),
        ),
        migrations.AddField(
            model_name='account_registration',
            name='password2',
            field=models.CharField(default='', max_length=20, verbose_name='password2'),
        ),
        migrations.AlterField(
            model_name='account_registration',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='email'),
        ),
    ]
