# Generated by Django 4.0.1 on 2022-02-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0003_alter_job_listing_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='interview',
            fields=[
                ('name', models.CharField(max_length=99, verbose_name='name')),
                ('applying_for', models.CharField(max_length=99, verbose_name='applying_for')),
                ('date_time', models.DateField(verbose_name='date_time')),
                ('email_add', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='email_add')),
            ],
        ),
    ]
