# Generated by Django 4.0.1 on 2022-04-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0003_remove_account_registration_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_registration',
            name='account_type',
            field=models.CharField(max_length=99, verbose_name='account_type'),
        ),
        migrations.AlterField(
            model_name='account_registration',
            name='applyingfor',
            field=models.CharField(choices=[('Choice1', 'Website Developersss')], default='', max_length=99, verbose_name='applyingfor'),
        ),
    ]
