# Generated by Django 4.0.1 on 2022-05-18 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0003_account_registration_password1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='email',
        ),
        migrations.RemoveField(
            model_name='other_info',
            name='email',
        ),
        migrations.AddField(
            model_name='interview',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='other_info',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
