# Generated by Django 4.0.4 on 2022-05-19 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0004_remove_interview_email_remove_other_info_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_registration',
            name='applyingfor',
            field=models.CharField(choices=[('Choice1', 'Website Developersss')], max_length=99, verbose_name='applyingfor'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='date_time',
            field=models.DateTimeField(default='Not yet set', null=True, verbose_name='date_time'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='first_name',
            field=models.CharField(max_length=99, null=True, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='jitle',
            field=models.ForeignKey(default='Not yet set', max_length=99, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobweb.job_listing', verbose_name='jtitle'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='last_name',
            field=models.CharField(max_length=99, null=True, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='middle_name',
            field=models.CharField(max_length=99, null=True, verbose_name='middle_name'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='NBI',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='NBI'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='SSS',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='SSS'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='TIN',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='TIN'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='bplace',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='bplace'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='citizenship',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='citizenship'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='civilstatus',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed')], default='Not yet set', max_length=99, null=True, verbose_name='civilstatus'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='college',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='college'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='college_grad',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='college_grad'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='company1',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='company1'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='company2',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='company2'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='e_contact',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='e_contact'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='e_no',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='e_no'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='elementary',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='elementary'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='elementary_grad',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='elementary_grad'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='from1',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='from_1'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='from2',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='from_2'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='highschool',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='highschool'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='highschool_grad',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='highschool_grad'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='med_record',
            field=models.CharField(default='Not yet set', max_length=6, null=True, verbose_name='med_record'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='pagibig',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='pagibig'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='philhealth',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='philhealth'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='position1',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='position1'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='position2',
            field=models.CharField(default='Not yet set', max_length=99, verbose_name='position2'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='ref1',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='ref1'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='ref2',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='ref2'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='refcom1',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='refcom1'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='refcom2',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='refcom2'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='refcon1',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='refcon1'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='refcon2',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='refcon2'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='refpos1',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='refpos1'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='refpos2',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='refpos2'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='religion',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='religion'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='signature',
            field=models.ImageField(blank=True, default='Not yet set', null=True, upload_to='', verbose_name='signature'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='to1',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='to_1'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='to2',
            field=models.CharField(default='Not yet set', max_length=99, null=True, verbose_name='to_2'),
        ),
    ]
