# Generated by Django 4.0.1 on 2022-02-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0004_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_listing',
            name='char_ref1',
            field=models.BooleanField(verbose_name='1_character_reference_needed'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='char_ref2',
            field=models.BooleanField(verbose_name='2_character_reference_needed'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='col_grad',
            field=models.BooleanField(verbose_name='college_graduate'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='hs_grad',
            field=models.BooleanField(verbose_name='highschool_graduate'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='no_char',
            field=models.BooleanField(verbose_name='no_character_reference_needed'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='no_dipl',
            field=models.BooleanField(verbose_name='no_diploma'),
        ),
    ]
