# Generated by Django 4.0.1 on 2022-04-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0004_alter_account_registration_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_registration',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo'),
        ),
    ]
