# Generated by Django 4.0.1 on 2022-04-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0005_alter_account_registration_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_registration',
            name='account_complete',
            field=models.BooleanField(default=False, verbose_name='account_complete'),
        ),
        migrations.AlterField(
            model_name='account_registration',
            name='password1',
            field=models.CharField(max_length=20, verbose_name='password1'),
        ),
        migrations.AlterField(
            model_name='account_registration',
            name='password2',
            field=models.CharField(max_length=20, verbose_name='password2'),
        ),
    ]
