# Generated by Django 4.0.1 on 2022-02-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0005_alter_job_listing_char_ref1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_data',
            name='ref1',
            field=models.CharField(default='', max_length=99, verbose_name='ref1'),
        ),
        migrations.AddField(
            model_name='account_data',
            name='ref2',
            field=models.CharField(default='', max_length=99, verbose_name='ref2'),
        ),
        migrations.AddField(
            model_name='account_data',
            name='refcom1',
            field=models.CharField(default='', max_length=99, verbose_name='refcom1'),
        ),
        migrations.AddField(
            model_name='account_data',
            name='refcom2',
            field=models.CharField(default='', max_length=99, verbose_name='refcom2'),
        ),
        migrations.AddField(
            model_name='account_data',
            name='refcon1',
            field=models.CharField(default='', max_length=99, verbose_name='refcon1'),
        ),
        migrations.AddField(
            model_name='account_data',
            name='refcon2',
            field=models.CharField(default='', max_length=99, verbose_name='refcon2'),
        ),
        migrations.AddField(
            model_name='account_data',
            name='refpos1',
            field=models.CharField(default='', max_length=99, verbose_name='refpos1'),
        ),
        migrations.AddField(
            model_name='account_data',
            name='refpos2',
            field=models.CharField(default='', max_length=99, verbose_name='refpos2'),
        ),
    ]
