# Generated by Django 4.0.4 on 2022-05-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0005_alter_account_registration_applyingfor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_info',
            name='med_record',
            field=models.CharField(max_length=6, null=True, verbose_name='med_record'),
        ),
    ]
