# Generated by Django 4.0.1 on 2022-04-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0006_account_registration_account_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_registration',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='account_pictures/', verbose_name='photo'),
        ),
    ]
