# Generated by Django 4.0.1 on 2022-02-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0006_account_data_ref1_account_data_ref2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_data',
            name='signature',
            field=models.ImageField(default='', upload_to='', verbose_name='signature'),
        ),
    ]
