# Generated by Django 4.0.1 on 2022-02-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0007_account_data_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_data',
            name='full_name',
        ),
        migrations.AddField(
            model_name='account_data',
            name='first_name',
            field=models.CharField(default='', max_length=99, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='account_data',
            name='last_name',
            field=models.CharField(default='', max_length=99, verbose_name='last_name'),
        ),
        migrations.AddField(
            model_name='account_data',
            name='middle_name',
            field=models.CharField(default='', max_length=99, verbose_name='middle_name'),
        ),
        migrations.AlterField(
            model_name='account_data',
            name='account_type',
            field=models.CharField(default='Applicant', max_length=99, verbose_name='account_type'),
        ),
        migrations.AlterField(
            model_name='account_data',
            name='job',
            field=models.CharField(default='Applicant', max_length=99, verbose_name='job'),
        ),
    ]
