# Generated by Django 4.0.1 on 2022-02-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0008_remove_account_data_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_listing',
            name='char_ref1',
        ),
        migrations.RemoveField(
            model_name='job_listing',
            name='char_ref2',
        ),
        migrations.RemoveField(
            model_name='job_listing',
            name='col_grad',
        ),
        migrations.RemoveField(
            model_name='job_listing',
            name='hs_grad',
        ),
        migrations.RemoveField(
            model_name='job_listing',
            name='no_char',
        ),
        migrations.RemoveField(
            model_name='job_listing',
            name='no_dipl',
        ),
        migrations.AddField(
            model_name='job_listing',
            name='jobreq1',
            field=models.CharField(default='No Diploma Needed', max_length=99, verbose_name='job requirement 1'),
        ),
        migrations.AddField(
            model_name='job_listing',
            name='jobreq2',
            field=models.CharField(default='No Reference Needed', max_length=99, verbose_name='job requirement 2'),
        ),
    ]
