# Generated by Django 4.0.4 on 2022-05-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0009_alter_other_info_nbi_alter_other_info_sss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_registration',
            name='birthday',
            field=models.DateField(null=True, verbose_name='birthday'),
        ),
    ]
