# Generated by Django 4.0.1 on 2022-04-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0009_alter_account_registration_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_registration',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='photo'),
        ),
    ]
