# Generated by Django 4.0.1 on 2022-02-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0009_remove_job_listing_char_ref1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_data',
            name='from1',
            field=models.CharField(max_length=99, verbose_name='from_1'),
        ),
        migrations.AlterField(
            model_name='account_data',
            name='from2',
            field=models.CharField(max_length=99, verbose_name='from_2'),
        ),
        migrations.AlterField(
            model_name='account_data',
            name='to1',
            field=models.CharField(max_length=99, verbose_name='to_1'),
        ),
        migrations.AlterField(
            model_name='account_data',
            name='to2',
            field=models.CharField(max_length=99, verbose_name='to_2'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='jdesc',
            field=models.TextField(max_length=300, verbose_name='jdesc'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='jobreq1',
            field=models.CharField(default='No Diploma Needed', max_length=99, verbose_name='jobreq1'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='jobreq2',
            field=models.CharField(default='No Reference Needed', max_length=99, verbose_name='jobreq2'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='jtitle',
            field=models.CharField(max_length=99, primary_key=True, serialize=False, verbose_name='jtitle'),
        ),
    ]
