# Generated by Django 4.0.4 on 2022-05-20 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0011_alter_other_info_nbi_alter_other_info_sss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='first_name',
            field=models.CharField(max_length=99, null=True, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='jitle',
            field=models.ForeignKey(max_length=99, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobweb.job_listing', verbose_name='jtitle'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='last_name',
            field=models.CharField(max_length=99, null=True, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='middle_name',
            field=models.CharField(max_length=99, null=True, verbose_name='middle_name'),
        ),
    ]
