# Generated by Django 4.0.1 on 2022-04-30 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0011_account_registration_employment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date_time',
            field=models.DateTimeField(null=True, verbose_name='date_time'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='jitle',
            field=models.ForeignKey(default='job title', max_length=99, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobweb.job_listing', verbose_name='jtitle'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='name',
            field=models.CharField(max_length=99, null=True, verbose_name='name'),
        ),
    ]
