# Generated by Django 4.0.4 on 2022-05-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0012_alter_interview_first_name_alter_interview_jitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_registration',
            name='photo',
            field=models.ImageField(null=True, upload_to='picture/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='signature',
            field=models.ImageField(null=True, upload_to='signature/', verbose_name='signature'),
        ),
    ]
