# Generated by Django 4.0.1 on 2022-04-30 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0012_alter_interview_date_time_alter_interview_jitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_registration',
            name='account_complete',
        ),
    ]
