# Generated by Django 4.0.1 on 2022-05-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0013_remove_account_registration_account_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date_time',
            field=models.DateTimeField(default='Not yet set.', null=True, verbose_name='date_time'),
        ),
    ]
