# Generated by Django 4.0.1 on 2022-05-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0014_alter_interview_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date_time',
            field=models.DateTimeField(null=True, verbose_name='date_time'),
        ),
    ]
