# Generated by Django 4.0.1 on 2022-05-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0015_alter_interview_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='name',
        ),
        migrations.AddField(
            model_name='interview',
            name='first_name',
            field=models.CharField(default='', max_length=99, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='interview',
            name='last_name',
            field=models.CharField(default='', max_length=99, verbose_name='last_name'),
        ),
        migrations.AddField(
            model_name='interview',
            name='middle_name',
            field=models.CharField(default='', max_length=99, verbose_name='middle_name'),
        ),
    ]
