# Generated by Django 4.0.1 on 2022-05-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0017_alter_interview_first_name_alter_interview_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='interview',
            name='name',
            field=models.CharField(max_length=99, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='NBI',
            field=models.IntegerField(max_length=6, null=True, verbose_name='NBI'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='SSS',
            field=models.IntegerField(max_length=10, null=True, verbose_name='SSS'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='TIN',
            field=models.IntegerField(max_length=9, null=True, verbose_name='TIN'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='bplace',
            field=models.CharField(max_length=99, null=True, verbose_name='bplace'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='citizenship',
            field=models.CharField(max_length=99, null=True, verbose_name='citizenship'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='civilstatus',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed')], max_length=99, null=True, verbose_name='civilstatus'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='college',
            field=models.CharField(max_length=99, null=True, verbose_name='college'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='college_grad',
            field=models.IntegerField(max_length=99, null=True, verbose_name='college_grad'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='company1',
            field=models.CharField(max_length=99, null=True, verbose_name='company1'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='company2',
            field=models.CharField(default='', max_length=99, null=True, verbose_name='company2'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='e_contact',
            field=models.CharField(max_length=99, null=True, verbose_name='e_contact'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='e_no',
            field=models.IntegerField(max_length=11, null=True, verbose_name='e_no'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='elementary',
            field=models.CharField(max_length=99, null=True, verbose_name='elementary'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='elementary_grad',
            field=models.IntegerField(max_length=99, null=True, verbose_name='elementary_grad'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='from1',
            field=models.CharField(max_length=99, null=True, verbose_name='from_1'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='from2',
            field=models.CharField(default='', max_length=99, null=True, verbose_name='from_2'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='highschool',
            field=models.CharField(max_length=99, null=True, verbose_name='highschool'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='highschool_grad',
            field=models.IntegerField(max_length=99, null=True, verbose_name='highschool_grad'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='med_record',
            field=models.CharField(max_length=6, null=True, verbose_name='med_record'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='pagibig',
            field=models.IntegerField(max_length=12, null=True, verbose_name='pagibig'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='philhealth',
            field=models.IntegerField(max_length=12, null=True, verbose_name='philhealth'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='position1',
            field=models.CharField(max_length=99, null=True, verbose_name='position1'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='ref1',
            field=models.CharField(default='', max_length=99, null=True, verbose_name='ref1'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='ref2',
            field=models.CharField(default='', max_length=99, null=True, verbose_name='ref2'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='refcom1',
            field=models.CharField(default='', max_length=99, null=True, verbose_name='refcom1'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='refcom2',
            field=models.CharField(default='', max_length=99, null=True, verbose_name='refcom2'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='refcon1',
            field=models.IntegerField(default='', max_length=11, null=True, verbose_name='refcon1'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='refcon2',
            field=models.IntegerField(default='', max_length=11, null=True, verbose_name='refcon2'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='refpos1',
            field=models.CharField(default='', max_length=99, null=True, verbose_name='refpos1'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='refpos2',
            field=models.CharField(default='', max_length=99, null=True, verbose_name='refpos2'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='religion',
            field=models.CharField(max_length=99, null=True, verbose_name='religion'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='signature',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='signature'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='to1',
            field=models.CharField(default='', max_length=99, null=True, verbose_name='to_1'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='to2',
            field=models.CharField(default='', max_length=99, null=True, verbose_name='to_2'),
        ),
    ]
