# Generated by Django 4.0.4 on 2022-05-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0019_alter_other_info_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_info',
            name='position2',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='position2'),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signature/', verbose_name='signature'),
        ),
    ]
