# Generated by Django 4.0.1 on 2022-05-05 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0020_remove_interview_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='middle_name',
        ),
    ]
