# Generated by Django 4.0.4 on 2022-05-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0021_alter_other_info_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_registration',
            name='applyingfor',
            field=models.CharField(blank=True, default='', max_length=99, verbose_name='applyingfor'),
        ),
    ]
