# Generated by Django 4.0.4 on 2022-05-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0022_alter_account_registration_applyingfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_registration',
            name='applyingfor',
            field=models.CharField(choices=[('Choice1', 'Please select here')], default='', max_length=99, verbose_name='applyingfor'),
        ),
    ]
