# Generated by Django 4.0.4 on 2022-05-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0023_alter_account_registration_applyingfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_registration',
            name='applyingfor',
            field=models.CharField(default='', max_length=99, verbose_name='applyingfor'),
        ),
    ]
