# Generated by Django 4.0.1 on 2022-05-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0024_remove_account_registration_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_registration',
            name='first_name',
            field=models.CharField(default='', max_length=99, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='interview',
            name='first_name',
            field=models.CharField(default='', max_length=99, null=True, verbose_name='first_name'),
        ),
    ]
