# Generated by Django 4.0.4 on 2022-05-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0024_alter_account_registration_applyingfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='other_info',
            name='verified_user',
            field=models.BooleanField(default=False, max_length=99, verbose_name='verified_user'),
        ),
    ]
