# Generated by Django 4.0.1 on 2022-05-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0025_account_registration_first_name_interview_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_info',
            name='position2',
            field=models.CharField(default='', max_length=99, verbose_name='position2'),
        ),
    ]
